ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/elastic-agent/elastic-agent:${ELASTIC_VERSION:-8.15.1}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
